#!/bin/bash
#
#    descarga peliculas de 180uplaod
#

# entrada
URL="$1"

# obtiene la ID
ID=$(echo $URL | sed 's/^.*\///')

# descarga el nombre de la pelicula
NOMBRE=wget $URL -O - | grep -i "<title>" | sed 's/^.*>\(.*\)<\/.*$/\1/; s/^Watch\ //; s/mp4$//g;'

# descarga la pelicula
wget -cq "http://180upload.com/vidembed-$ID.mp4" -O "$NOMBRE-$ID.mp4" # descarga la pelicula solo una vez
