#!/bin/bash
#
#       Descarga videos de vk
#       Ernesto Bazzano (El Bazza)- Licencia AGPL
#       basado en el trabajo de Dzup para u3mx.com
#

# descarga el contenido de laa pagina de embed
html=$(wget "$1" -qO -)

# obtiene variables
echo "vtag
uid
host
title"| while read NOMBRE; do
        eval $NOMBRE=$(echo "$html" | grep "var video_$NOMBRE" | sed "s/^.*'\(.*\)'.*$/\1/g")
done

if [ $vtag ]; then
        # descarga la pelicula con un nombre mas lindo
        wget ${host}/u${uid}/video/${vtag}.360.mp4 -O "${title}-${vtag}.mp4"
fi
