
INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('the greatest love 16', 'TheGreatestLoveOnlineTelenovelaTheGreatestLoveVerTheGreatestLove', 'The Greatest Love Online Telenovela The Greatest Love Ver The Greatest Love', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'Ae Jung (Gong Hyo Jin) es una ex miembro de una banda femenina disuelta de repente. A ella se la culpa de la súbita separación, y tras varios escándalos, Ae Jung se ha convertido en una celebridad no muy querida. Después de años de sobrevivir en el mundo del espectáculo realizando trabajos de lo más humillante, sin el amor de la gente, conoce a Dok Ko Jin (Cha Seung Won), una estrella Hallyu, vanidoso y arrogante, y termina envolviéndose en un escándalo con él. En medio de los malentendidos, las cosas se complican aún más cuando Dok Ko Jin reconoce avergonzado que su corazón ha sido capturado por Ae Jung, aunque eso no tenga mucho sentido para él. El problema es que, a pesar del éxito y lo irresistible que Ko Jin sea para todo Korea, ella no está para nada interesada...', 'http://vertelenovelas.net/image_files/the-greatest-love.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xkeywl?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div><div id="tab1_2" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xkf05r?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div><div id="tab1_3" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xkf1bv?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div><div id="tab1_4" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xkf25q?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (1 : 1350342318) capitulo/the-greatest-love-16.html http://vertelenovelas.net/image_files/the-greatest-love.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> the-greatest-love.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('the greatest love 16', 'TheGreatestLoveOnlineTelenovelaTheGreatestLoveVerTheGreatestLove', 'The Greatest Love Online Telenovela The Greatest Love Ver The Greatest Love', '', 'tv, telenovela, tvnovela, , dialymotion', 'Ae Jung (Gong Hyo Jin) es una ex miembro de una banda femenina disuelta de repente. A ella se la culpa de la súbita separación, y tras varios escándalos, Ae Jung se ha convertido en una celebridad no muy querida. Después de años de sobrevivir en el mundo del espectáculo realizando trabajos de lo más humillante, sin el amor de la gente, conoce a Dok Ko Jin (Cha Seung Won), una estrella Hallyu, vanidoso y arrogante, y termina envolviéndose en un escándalo con él. En medio de los malentendidos, las cosas se complican aún más cuando Dok Ko Jin reconoce avergonzado que su corazón ha sido capturado por Ae Jung, aunque eso no tenga mucho sentido para él. El problema es que, a pesar del éxito y lo irresistible que Ko Jin sea para todo Korea, ella no está para nada interesada...', 'http://vertelenovelas.net/image_files/the-greatest-love.jpg', ' <iframe src="http://www.dailymotion.com/embed/video/xkeywl?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe> <iframe src="http://www.dailymotion.com/embed/video/xkf05r?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe> <iframe src="http://www.dailymotion.com/embed/video/xkf1bv?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe> <iframe src="http://www.dailymotion.com/embed/video/xkf25q?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (1 : 1350342318) capitulo/the-greatest-love-16.html http://vertelenovelas.net/image_files/the-greatest-love.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> the-greatest-love.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('the greatest love 15', 'TheGreatestLoveOnlineTelenovelaTheGreatestLoveVerTheGreatestLove', 'The Greatest Love Online Telenovela The Greatest Love Ver The Greatest Love', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'Ae Jung (Gong Hyo Jin) es una ex miembro de una banda femenina disuelta de repente. A ella se la culpa de la súbita separación, y tras varios escándalos, Ae Jung se ha convertido en una celebridad no muy querida. Después de años de sobrevivir en el mundo del espectáculo realizando trabajos de lo más humillante, sin el amor de la gente, conoce a Dok Ko Jin (Cha Seung Won), una estrella Hallyu, vanidoso y arrogante, y termina envolviéndose en un escándalo con él. En medio de los malentendidos, las cosas se complican aún más cuando Dok Ko Jin reconoce avergonzado que su corazón ha sido capturado por Ae Jung, aunque eso no tenga mucho sentido para él. El problema es que, a pesar del éxito y lo irresistible que Ko Jin sea para todo Korea, ella no está para nada interesada...', 'http://vertelenovelas.net/image_files/the-greatest-love.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xkcvh8?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div><div id="tab1_2" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xkcwm8?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div><div id="tab1_3" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xkcww8?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div><div id="tab1_4" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xkd7b0?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (2 : 1350342318) capitulo/the-greatest-love-15.html http://vertelenovelas.net/image_files/the-greatest-love.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> the-greatest-love.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('the greatest love 15', 'TheGreatestLoveOnlineTelenovelaTheGreatestLoveVerTheGreatestLove', 'The Greatest Love Online Telenovela The Greatest Love Ver The Greatest Love', '', 'tv, telenovela, tvnovela, , dialymotion', 'Ae Jung (Gong Hyo Jin) es una ex miembro de una banda femenina disuelta de repente. A ella se la culpa de la súbita separación, y tras varios escándalos, Ae Jung se ha convertido en una celebridad no muy querida. Después de años de sobrevivir en el mundo del espectáculo realizando trabajos de lo más humillante, sin el amor de la gente, conoce a Dok Ko Jin (Cha Seung Won), una estrella Hallyu, vanidoso y arrogante, y termina envolviéndose en un escándalo con él. En medio de los malentendidos, las cosas se complican aún más cuando Dok Ko Jin reconoce avergonzado que su corazón ha sido capturado por Ae Jung, aunque eso no tenga mucho sentido para él. El problema es que, a pesar del éxito y lo irresistible que Ko Jin sea para todo Korea, ella no está para nada interesada...', 'http://vertelenovelas.net/image_files/the-greatest-love.jpg', ' <iframe src="http://www.dailymotion.com/embed/video/xkcvh8?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe> <iframe src="http://www.dailymotion.com/embed/video/xkcwm8?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe> <iframe src="http://www.dailymotion.com/embed/video/xkcww8?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe> <iframe src="http://www.dailymotion.com/embed/video/xkd7b0?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (2 : 1350342318) capitulo/the-greatest-love-15.html http://vertelenovelas.net/image_files/the-greatest-love.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> the-greatest-love.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('the greatest love 14', 'TheGreatestLoveOnlineTelenovelaTheGreatestLoveVerTheGreatestLove', 'The Greatest Love Online Telenovela The Greatest Love Ver The Greatest Love', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'Ae Jung (Gong Hyo Jin) es una ex miembro de una banda femenina disuelta de repente. A ella se la culpa de la súbita separación, y tras varios escándalos, Ae Jung se ha convertido en una celebridad no muy querida. Después de años de sobrevivir en el mundo del espectáculo realizando trabajos de lo más humillante, sin el amor de la gente, conoce a Dok Ko Jin (Cha Seung Won), una estrella Hallyu, vanidoso y arrogante, y termina envolviéndose en un escándalo con él. En medio de los malentendidos, las cosas se complican aún más cuando Dok Ko Jin reconoce avergonzado que su corazón ha sido capturado por Ae Jung, aunque eso no tenga mucho sentido para él. El problema es que, a pesar del éxito y lo irresistible que Ko Jin sea para todo Korea, ella no está para nada interesada...', 'http://vertelenovelas.net/image_files/the-greatest-love.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xk3bq7?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div><div id="tab1_2" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xk3ch9?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div><div id="tab1_3" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xk3rj8?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div><div id="tab1_4" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xk3rj9?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (3 : 1350342319) capitulo/the-greatest-love-14.html http://vertelenovelas.net/image_files/the-greatest-love.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> the-greatest-love.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('the greatest love 14', 'TheGreatestLoveOnlineTelenovelaTheGreatestLoveVerTheGreatestLove', 'The Greatest Love Online Telenovela The Greatest Love Ver The Greatest Love', '', 'tv, telenovela, tvnovela, , dialymotion', 'Ae Jung (Gong Hyo Jin) es una ex miembro de una banda femenina disuelta de repente. A ella se la culpa de la súbita separación, y tras varios escándalos, Ae Jung se ha convertido en una celebridad no muy querida. Después de años de sobrevivir en el mundo del espectáculo realizando trabajos de lo más humillante, sin el amor de la gente, conoce a Dok Ko Jin (Cha Seung Won), una estrella Hallyu, vanidoso y arrogante, y termina envolviéndose en un escándalo con él. En medio de los malentendidos, las cosas se complican aún más cuando Dok Ko Jin reconoce avergonzado que su corazón ha sido capturado por Ae Jung, aunque eso no tenga mucho sentido para él. El problema es que, a pesar del éxito y lo irresistible que Ko Jin sea para todo Korea, ella no está para nada interesada...', 'http://vertelenovelas.net/image_files/the-greatest-love.jpg', ' <iframe src="http://www.dailymotion.com/embed/video/xk3bq7?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe> <iframe src="http://www.dailymotion.com/embed/video/xk3ch9?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe> <iframe src="http://www.dailymotion.com/embed/video/xk3rj8?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe> <iframe src="http://www.dailymotion.com/embed/video/xk3rj9?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (3 : 1350342319) capitulo/the-greatest-love-14.html http://vertelenovelas.net/image_files/the-greatest-love.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> the-greatest-love.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('the greatest love 13', 'TheGreatestLoveOnlineTelenovelaTheGreatestLoveVerTheGreatestLove', 'The Greatest Love Online Telenovela The Greatest Love Ver The Greatest Love', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'Ae Jung (Gong Hyo Jin) es una ex miembro de una banda femenina disuelta de repente. A ella se la culpa de la súbita separación, y tras varios escándalos, Ae Jung se ha convertido en una celebridad no muy querida. Después de años de sobrevivir en el mundo del espectáculo realizando trabajos de lo más humillante, sin el amor de la gente, conoce a Dok Ko Jin (Cha Seung Won), una estrella Hallyu, vanidoso y arrogante, y termina envolviéndose en un escándalo con él. En medio de los malentendidos, las cosas se complican aún más cuando Dok Ko Jin reconoce avergonzado que su corazón ha sido capturado por Ae Jung, aunque eso no tenga mucho sentido para él. El problema es que, a pesar del éxito y lo irresistible que Ko Jin sea para todo Korea, ella no está para nada interesada...', 'http://vertelenovelas.net/image_files/the-greatest-love.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xjy7ap?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div><div id="tab1_2" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xjy7as?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div><div id="tab1_3" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xjy8j6?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div><div id="tab1_4" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xjy9nn?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (4 : 1350342319) capitulo/the-greatest-love-13.html http://vertelenovelas.net/image_files/the-greatest-love.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> the-greatest-love.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('the greatest love 13', 'TheGreatestLoveOnlineTelenovelaTheGreatestLoveVerTheGreatestLove', 'The Greatest Love Online Telenovela The Greatest Love Ver The Greatest Love', '', 'tv, telenovela, tvnovela, , dialymotion', 'Ae Jung (Gong Hyo Jin) es una ex miembro de una banda femenina disuelta de repente. A ella se la culpa de la súbita separación, y tras varios escándalos, Ae Jung se ha convertido en una celebridad no muy querida. Después de años de sobrevivir en el mundo del espectáculo realizando trabajos de lo más humillante, sin el amor de la gente, conoce a Dok Ko Jin (Cha Seung Won), una estrella Hallyu, vanidoso y arrogante, y termina envolviéndose en un escándalo con él. En medio de los malentendidos, las cosas se complican aún más cuando Dok Ko Jin reconoce avergonzado que su corazón ha sido capturado por Ae Jung, aunque eso no tenga mucho sentido para él. El problema es que, a pesar del éxito y lo irresistible que Ko Jin sea para todo Korea, ella no está para nada interesada...', 'http://vertelenovelas.net/image_files/the-greatest-love.jpg', ' <iframe src="http://www.dailymotion.com/embed/video/xjy7ap?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe> <iframe src="http://www.dailymotion.com/embed/video/xjy7as?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe> <iframe src="http://www.dailymotion.com/embed/video/xjy8j6?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe> <iframe src="http://www.dailymotion.com/embed/video/xjy9nn?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (4 : 1350342319) capitulo/the-greatest-love-13.html http://vertelenovelas.net/image_files/the-greatest-love.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> the-greatest-love.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('the greatest love 12', 'TheGreatestLoveOnlineTelenovelaTheGreatestLoveVerTheGreatestLove', 'The Greatest Love Online Telenovela The Greatest Love Ver The Greatest Love', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'Ae Jung (Gong Hyo Jin) es una ex miembro de una banda femenina disuelta de repente. A ella se la culpa de la súbita separación, y tras varios escándalos, Ae Jung se ha convertido en una celebridad no muy querida. Después de años de sobrevivir en el mundo del espectáculo realizando trabajos de lo más humillante, sin el amor de la gente, conoce a Dok Ko Jin (Cha Seung Won), una estrella Hallyu, vanidoso y arrogante, y termina envolviéndose en un escándalo con él. En medio de los malentendidos, las cosas se complican aún más cuando Dok Ko Jin reconoce avergonzado que su corazón ha sido capturado por Ae Jung, aunque eso no tenga mucho sentido para él. El problema es que, a pesar del éxito y lo irresistible que Ko Jin sea para todo Korea, ella no está para nada interesada...', 'http://vertelenovelas.net/image_files/the-greatest-love.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xjv6fc?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div><div id="tab1_2" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xjv4fe?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div><div id="tab1_3" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xjv7eq?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div><div id="tab1_4" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xjvmxh?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (5 : 1350342320) capitulo/the-greatest-love-12.html http://vertelenovelas.net/image_files/the-greatest-love.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> the-greatest-love.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('the greatest love 12', 'TheGreatestLoveOnlineTelenovelaTheGreatestLoveVerTheGreatestLove', 'The Greatest Love Online Telenovela The Greatest Love Ver The Greatest Love', '', 'tv, telenovela, tvnovela, , dialymotion', 'Ae Jung (Gong Hyo Jin) es una ex miembro de una banda femenina disuelta de repente. A ella se la culpa de la súbita separación, y tras varios escándalos, Ae Jung se ha convertido en una celebridad no muy querida. Después de años de sobrevivir en el mundo del espectáculo realizando trabajos de lo más humillante, sin el amor de la gente, conoce a Dok Ko Jin (Cha Seung Won), una estrella Hallyu, vanidoso y arrogante, y termina envolviéndose en un escándalo con él. En medio de los malentendidos, las cosas se complican aún más cuando Dok Ko Jin reconoce avergonzado que su corazón ha sido capturado por Ae Jung, aunque eso no tenga mucho sentido para él. El problema es que, a pesar del éxito y lo irresistible que Ko Jin sea para todo Korea, ella no está para nada interesada...', 'http://vertelenovelas.net/image_files/the-greatest-love.jpg', ' <iframe src="http://www.dailymotion.com/embed/video/xjv6fc?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe> <iframe src="http://www.dailymotion.com/embed/video/xjv4fe?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe> <iframe src="http://www.dailymotion.com/embed/video/xjv7eq?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe> <iframe src="http://www.dailymotion.com/embed/video/xjvmxh?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (5 : 1350342320) capitulo/the-greatest-love-12.html http://vertelenovelas.net/image_files/the-greatest-love.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> the-greatest-love.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('the greatest love 11', 'TheGreatestLoveOnlineTelenovelaTheGreatestLoveVerTheGreatestLove', 'The Greatest Love Online Telenovela The Greatest Love Ver The Greatest Love', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'Ae Jung (Gong Hyo Jin) es una ex miembro de una banda femenina disuelta de repente. A ella se la culpa de la súbita separación, y tras varios escándalos, Ae Jung se ha convertido en una celebridad no muy querida. Después de años de sobrevivir en el mundo del espectáculo realizando trabajos de lo más humillante, sin el amor de la gente, conoce a Dok Ko Jin (Cha Seung Won), una estrella Hallyu, vanidoso y arrogante, y termina envolviéndose en un escándalo con él. En medio de los malentendidos, las cosas se complican aún más cuando Dok Ko Jin reconoce avergonzado que su corazón ha sido capturado por Ae Jung, aunque eso no tenga mucho sentido para él. El problema es que, a pesar del éxito y lo irresistible que Ko Jin sea para todo Korea, ella no está para nada interesada...', 'http://vertelenovelas.net/image_files/the-greatest-love.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xjnje0?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div><div id="tab1_2" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xjnje6?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div><div id="tab1_3" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xjnkc9?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div><div id="tab1_4" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xjnm1x?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (6 : 1350342320) capitulo/the-greatest-love-11.html http://vertelenovelas.net/image_files/the-greatest-love.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> the-greatest-love.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('the greatest love 11', 'TheGreatestLoveOnlineTelenovelaTheGreatestLoveVerTheGreatestLove', 'The Greatest Love Online Telenovela The Greatest Love Ver The Greatest Love', '', 'tv, telenovela, tvnovela, , dialymotion', 'Ae Jung (Gong Hyo Jin) es una ex miembro de una banda femenina disuelta de repente. A ella se la culpa de la súbita separación, y tras varios escándalos, Ae Jung se ha convertido en una celebridad no muy querida. Después de años de sobrevivir en el mundo del espectáculo realizando trabajos de lo más humillante, sin el amor de la gente, conoce a Dok Ko Jin (Cha Seung Won), una estrella Hallyu, vanidoso y arrogante, y termina envolviéndose en un escándalo con él. En medio de los malentendidos, las cosas se complican aún más cuando Dok Ko Jin reconoce avergonzado que su corazón ha sido capturado por Ae Jung, aunque eso no tenga mucho sentido para él. El problema es que, a pesar del éxito y lo irresistible que Ko Jin sea para todo Korea, ella no está para nada interesada...', 'http://vertelenovelas.net/image_files/the-greatest-love.jpg', ' <iframe src="http://www.dailymotion.com/embed/video/xjnje0?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe> <iframe src="http://www.dailymotion.com/embed/video/xjnje6?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe> <iframe src="http://www.dailymotion.com/embed/video/xjnkc9?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe> <iframe src="http://www.dailymotion.com/embed/video/xjnm1x?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (6 : 1350342320) capitulo/the-greatest-love-11.html http://vertelenovelas.net/image_files/the-greatest-love.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> the-greatest-love.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('the greatest love 10', 'TheGreatestLoveOnlineTelenovelaTheGreatestLoveVerTheGreatestLove', 'The Greatest Love Online Telenovela The Greatest Love Ver The Greatest Love', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'Ae Jung (Gong Hyo Jin) es una ex miembro de una banda femenina disuelta de repente. A ella se la culpa de la súbita separación, y tras varios escándalos, Ae Jung se ha convertido en una celebridad no muy querida. Después de años de sobrevivir en el mundo del espectáculo realizando trabajos de lo más humillante, sin el amor de la gente, conoce a Dok Ko Jin (Cha Seung Won), una estrella Hallyu, vanidoso y arrogante, y termina envolviéndose en un escándalo con él. En medio de los malentendidos, las cosas se complican aún más cuando Dok Ko Jin reconoce avergonzado que su corazón ha sido capturado por Ae Jung, aunque eso no tenga mucho sentido para él. El problema es que, a pesar del éxito y lo irresistible que Ko Jin sea para todo Korea, ella no está para nada interesada...', 'http://vertelenovelas.net/image_files/the-greatest-love.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xjgv4q?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div><div id="tab1_2" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xjgvq3?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div><div id="tab1_3" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xjgxko?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div><div id="tab1_4" class="subtab_content" style="display: block;"><iframe frameborder="0" width="680" height="430" src="http://www.dailymotion.com/embed/video/xjgxux?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9"></iframe></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (7 : 1350342321) capitulo/the-greatest-love-10.html http://vertelenovelas.net/image_files/the-greatest-love.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> the-greatest-love.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('the greatest love 10', 'TheGreatestLoveOnlineTelenovelaTheGreatestLoveVerTheGreatestLove', 'The Greatest Love Online Telenovela The Greatest Love Ver The Greatest Love', '', 'tv, telenovela, tvnovela, , dialymotion', 'Ae Jung (Gong Hyo Jin) es una ex miembro de una banda femenina disuelta de repente. A ella se la culpa de la súbita separación, y tras varios escándalos, Ae Jung se ha convertido en una celebridad no muy querida. Después de años de sobrevivir en el mundo del espectáculo realizando trabajos de lo más humillante, sin el amor de la gente, conoce a Dok Ko Jin (Cha Seung Won), una estrella Hallyu, vanidoso y arrogante, y termina envolviéndose en un escándalo con él. En medio de los malentendidos, las cosas se complican aún más cuando Dok Ko Jin reconoce avergonzado que su corazón ha sido capturado por Ae Jung, aunque eso no tenga mucho sentido para él. El problema es que, a pesar del éxito y lo irresistible que Ko Jin sea para todo Korea, ella no está para nada interesada...', 'http://vertelenovelas.net/image_files/the-greatest-love.jpg', ' <iframe src="http://www.dailymotion.com/embed/video/xjgv4q?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe> <iframe src="http://www.dailymotion.com/embed/video/xjgvq3?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe> <iframe src="http://www.dailymotion.com/embed/video/xjgxko?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe> <iframe src="http://www.dailymotion.com/embed/video/xjgxux?theme=harris&foreground=%23FFFFFF&highlight=%23C9A1FF&background=%23FB63B9" width="807" height="360" frameborder="0"></iframe>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (7 : 1350342321) capitulo/the-greatest-love-10.html http://vertelenovelas.net/image_files/the-greatest-love.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> the-greatest-love.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('the greatest love 9', 'TheGreatestLoveOnlineTelenovelaTheGreatestLoveVerTheGreatestLove', 'The Greatest Love Online Telenovela The Greatest Love Ver The Greatest Love', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'Ae Jung (Gong Hyo Jin) es una ex miembro de una banda femenina disuelta de repente. A ella se la culpa de la súbita separación, y tras varios escándalos, Ae Jung se ha convertido en una celebridad no muy querida. Después de años de sobrevivir en el mundo del espectáculo realizando trabajos de lo más humillante, sin el amor de la gente, conoce a Dok Ko Jin (Cha Seung Won), una estrella Hallyu, vanidoso y arrogante, y termina envolviéndose en un escándalo con él. En medio de los malentendidos, las cosas se complican aún más cuando Dok Ko Jin reconoce avergonzado que su corazón ha sido capturado por Ae Jung, aunque eso no tenga mucho sentido para él. El problema es que, a pesar del éxito y lo irresistible que Ko Jin sea para todo Korea, ella no está para nada interesada...', 'http://vertelenovelas.net/image_files/the-greatest-love.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2111041690828.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2111343778380.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2111351698578.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2111517702728.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (8 : 1350342322) capitulo/the-greatest-love-9.html http://vertelenovelas.net/image_files/the-greatest-love.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> the-greatest-love.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('the greatest love 8', 'TheGreatestLoveOnlineTelenovelaTheGreatestLoveVerTheGreatestLove', 'The Greatest Love Online Telenovela The Greatest Love Ver The Greatest Love', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'Ae Jung (Gong Hyo Jin) es una ex miembro de una banda femenina disuelta de repente. A ella se la culpa de la súbita separación, y tras varios escándalos, Ae Jung se ha convertido en una celebridad no muy querida. Después de años de sobrevivir en el mundo del espectáculo realizando trabajos de lo más humillante, sin el amor de la gente, conoce a Dok Ko Jin (Cha Seung Won), una estrella Hallyu, vanidoso y arrogante, y termina envolviéndose en un escándalo con él. En medio de los malentendidos, las cosas se complican aún más cuando Dok Ko Jin reconoce avergonzado que su corazón ha sido capturado por Ae Jung, aunque eso no tenga mucho sentido para él. El problema es que, a pesar del éxito y lo irresistible que Ko Jin sea para todo Korea, ella no está para nada interesada...', 'http://vertelenovelas.net/image_files/the-greatest-love.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2100308662509.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2100276621708.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2100361383827.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2100456106195.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (9 : 1350342322) capitulo/the-greatest-love-8.html http://vertelenovelas.net/image_files/the-greatest-love.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> the-greatest-love.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('the greatest love 7', 'TheGreatestLoveOnlineTelenovelaTheGreatestLoveVerTheGreatestLove', 'The Greatest Love Online Telenovela The Greatest Love Ver The Greatest Love', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'Ae Jung (Gong Hyo Jin) es una ex miembro de una banda femenina disuelta de repente. A ella se la culpa de la súbita separación, y tras varios escándalos, Ae Jung se ha convertido en una celebridad no muy querida. Después de años de sobrevivir en el mundo del espectáculo realizando trabajos de lo más humillante, sin el amor de la gente, conoce a Dok Ko Jin (Cha Seung Won), una estrella Hallyu, vanidoso y arrogante, y termina envolviéndose en un escándalo con él. En medio de los malentendidos, las cosas se complican aún más cuando Dok Ko Jin reconoce avergonzado que su corazón ha sido capturado por Ae Jung, aunque eso no tenga mucho sentido para él. El problema es que, a pesar del éxito y lo irresistible que Ko Jin sea para todo Korea, ella no está para nada interesada...', 'http://vertelenovelas.net/image_files/the-greatest-love.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2057822520382.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2057865001444.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2058708902541.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2058845705961.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (10 : 1350342323) capitulo/the-greatest-love-7.html http://vertelenovelas.net/image_files/the-greatest-love.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> the-greatest-love.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('the greatest love 6', 'TheGreatestLoveOnlineTelenovelaTheGreatestLoveVerTheGreatestLove', 'The Greatest Love Online Telenovela The Greatest Love Ver The Greatest Love', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'Ae Jung (Gong Hyo Jin) es una ex miembro de una banda femenina disuelta de repente. A ella se la culpa de la súbita separación, y tras varios escándalos, Ae Jung se ha convertido en una celebridad no muy querida. Después de años de sobrevivir en el mundo del espectáculo realizando trabajos de lo más humillante, sin el amor de la gente, conoce a Dok Ko Jin (Cha Seung Won), una estrella Hallyu, vanidoso y arrogante, y termina envolviéndose en un escándalo con él. En medio de los malentendidos, las cosas se complican aún más cuando Dok Ko Jin reconoce avergonzado que su corazón ha sido capturado por Ae Jung, aunque eso no tenga mucho sentido para él. El problema es que, a pesar del éxito y lo irresistible que Ko Jin sea para todo Korea, ella no está para nada interesada...', 'http://vertelenovelas.net/image_files/the-greatest-love.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2046331793121.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2046331913124.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2046429235557.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2046429395561.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (11 : 1350342324) capitulo/the-greatest-love-6.html http://vertelenovelas.net/image_files/the-greatest-love.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> the-greatest-love.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('the greatest love 5', 'TheGreatestLoveOnlineTelenovelaTheGreatestLoveVerTheGreatestLove', 'The Greatest Love Online Telenovela The Greatest Love Ver The Greatest Love', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'Ae Jung (Gong Hyo Jin) es una ex miembro de una banda femenina disuelta de repente. A ella se la culpa de la súbita separación, y tras varios escándalos, Ae Jung se ha convertido en una celebridad no muy querida. Después de años de sobrevivir en el mundo del espectáculo realizando trabajos de lo más humillante, sin el amor de la gente, conoce a Dok Ko Jin (Cha Seung Won), una estrella Hallyu, vanidoso y arrogante, y termina envolviéndose en un escándalo con él. En medio de los malentendidos, las cosas se complican aún más cuando Dok Ko Jin reconoce avergonzado que su corazón ha sido capturado por Ae Jung, aunque eso no tenga mucho sentido para él. El problema es que, a pesar del éxito y lo irresistible que Ko Jin sea para todo Korea, ella no está para nada interesada...', 'http://vertelenovelas.net/image_files/the-greatest-love.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2033770719102.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2033771239115.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2033878401794.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2033878561798.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (12 : 1350342324) capitulo/the-greatest-love-5.html http://vertelenovelas.net/image_files/the-greatest-love.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> the-greatest-love.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('the greatest love 4', 'TheGreatestLoveOnlineTelenovelaTheGreatestLoveVerTheGreatestLove', 'The Greatest Love Online Telenovela The Greatest Love Ver The Greatest Love', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'Ae Jung (Gong Hyo Jin) es una ex miembro de una banda femenina disuelta de repente. A ella se la culpa de la súbita separación, y tras varios escándalos, Ae Jung se ha convertido en una celebridad no muy querida. Después de años de sobrevivir en el mundo del espectáculo realizando trabajos de lo más humillante, sin el amor de la gente, conoce a Dok Ko Jin (Cha Seung Won), una estrella Hallyu, vanidoso y arrogante, y termina envolviéndose en un escándalo con él. En medio de los malentendidos, las cosas se complican aún más cuando Dok Ko Jin reconoce avergonzado que su corazón ha sido capturado por Ae Jung, aunque eso no tenga mucho sentido para él. El problema es que, a pesar del éxito y lo irresistible que Ko Jin sea para todo Korea, ella no está para nada interesada...', 'http://vertelenovelas.net/image_files/the-greatest-love.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2025099022315.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2025099742333.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2025294707207.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2025372669156.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (13 : 1350342325) capitulo/the-greatest-love-4.html http://vertelenovelas.net/image_files/the-greatest-love.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> the-greatest-love.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('the greatest love 3', 'TheGreatestLoveOnlineTelenovelaTheGreatestLoveVerTheGreatestLove', 'The Greatest Love Online Telenovela The Greatest Love Ver The Greatest Love', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'Ae Jung (Gong Hyo Jin) es una ex miembro de una banda femenina disuelta de repente. A ella se la culpa de la súbita separación, y tras varios escándalos, Ae Jung se ha convertido en una celebridad no muy querida. Después de años de sobrevivir en el mundo del espectáculo realizando trabajos de lo más humillante, sin el amor de la gente, conoce a Dok Ko Jin (Cha Seung Won), una estrella Hallyu, vanidoso y arrogante, y termina envolviéndose en un escándalo con él. En medio de los malentendidos, las cosas se complican aún más cuando Dok Ko Jin reconoce avergonzado que su corazón ha sido capturado por Ae Jung, aunque eso no tenga mucho sentido para él. El problema es que, a pesar del éxito y lo irresistible que Ko Jin sea para todo Korea, ella no está para nada interesada...', 'http://vertelenovelas.net/image_files/the-greatest-love.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2014999769840.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2015000009846.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2015081931894.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2015082331904.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (14 : 1350342325) capitulo/the-greatest-love-3.html http://vertelenovelas.net/image_files/the-greatest-love.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> the-greatest-love.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('the greatest love 2', 'TheGreatestLoveOnlineTelenovelaTheGreatestLoveVerTheGreatestLove', 'The Greatest Love Online Telenovela The Greatest Love Ver The Greatest Love', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'Ae Jung (Gong Hyo Jin) es una ex miembro de una banda femenina disuelta de repente. A ella se la culpa de la súbita separación, y tras varios escándalos, Ae Jung se ha convertido en una celebridad no muy querida. Después de años de sobrevivir en el mundo del espectáculo realizando trabajos de lo más humillante, sin el amor de la gente, conoce a Dok Ko Jin (Cha Seung Won), una estrella Hallyu, vanidoso y arrogante, y termina envolviéndose en un escándalo con él. En medio de los malentendidos, las cosas se complican aún más cuando Dok Ko Jin reconoce avergonzado que su corazón ha sido capturado por Ae Jung, aunque eso no tenga mucho sentido para él. El problema es que, a pesar del éxito y lo irresistible que Ko Jin sea para todo Korea, ella no está para nada interesada...', 'http://vertelenovelas.net/image_files/the-greatest-love.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2007689467087.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2007689667092.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2007751628641.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/2007751948649.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (15 : 1350342326) capitulo/the-greatest-love-2.html http://vertelenovelas.net/image_files/the-greatest-love.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> the-greatest-love.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('the greatest love 1', 'TheGreatestLoveOnlineTelenovelaTheGreatestLoveVerTheGreatestLove', 'The Greatest Love Online Telenovela The Greatest Love Ver The Greatest Love', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'Ae Jung (Gong Hyo Jin) es una ex miembro de una banda femenina disuelta de repente. A ella se la culpa de la súbita separación, y tras varios escándalos, Ae Jung se ha convertido en una celebridad no muy querida. Después de años de sobrevivir en el mundo del espectáculo realizando trabajos de lo más humillante, sin el amor de la gente, conoce a Dok Ko Jin (Cha Seung Won), una estrella Hallyu, vanidoso y arrogante, y termina envolviéndose en un escándalo con él. En medio de los malentendidos, las cosas se complican aún más cuando Dok Ko Jin reconoce avergonzado que su corazón ha sido capturado por Ae Jung, aunque eso no tenga mucho sentido para él. El problema es que, a pesar del éxito y lo irresistible que Ko Jin sea para todo Korea, ella no está para nada interesada...', 'http://vertelenovelas.net/image_files/the-greatest-love.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/1998571639147.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/1998571759150.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/1998764683973.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed src="http://www.facebook.com/v/1998764923979.mp4" width="587" height="350" allowFullScreen="true" allownetworking="internal" type="application/x-shockwave-flash" wmode="transparent"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (16 : 1350342327) capitulo/the-greatest-love-1.html http://vertelenovelas.net/image_files/the-greatest-love.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> the-greatest-love.sql por Alex');

