
INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('vals de prlmavera 20', 'VALSDEPRlMAVERAOnlineTelenovelaVALSDEPRlMAVERAVerVALSDEPRlMAVERA', 'VALS DE PRlMAVERA Online Telenovela VALS DE PRlMAVERA Ver VALS DE PRlMAVERA', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'A Suh Eun-young (Han Hyo-joo) que vive con su madre soltera en un bello pueblo insular, le piden que cuide de Su-ho, el hijo del amigo de su madre, de su ciudad natal. Su-ho y Eun-young viven juntos y sienten amor fraternal, pero Eun-young, que es de naturaleza enfermiza desde su niñez, llega a un punto crítico de perder su vida si no recibe una operación quirúrgica. Debido a que su familia es extremadamente pobre, son incapaces de pagar los elevados gastos médicos para la hospitalización y el tratamiento quirúrgico y se enfrentan a un callejón sin salida. Afortunadamente, un hombre y su esposa, que desean pagar los gastos médicos de Eun-young, aparecen frente a la familia. Son los padres de Yoon Jae-ha, que hace poco perdieron a su único hijo, internado en el hospital. Ellos proponen pagar los gastos médicos de Eun-young, con la condición de adoptar a Su-ho, quien se parece exactamente a su difunto hijo. Su-ho, que quiere salvar a Eun-young, se marcha a Austria con ellos y Eun-young se recupera totalmente.', 'http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li><li><a href="#tab1_5">Parte 5</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/1IUeZSHHve4&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/qzBs9P8jrsA&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/sbD1klFY_1Y&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/uNScyJjDa0I&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_5" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/jHgyeRl7QbA&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (1 : 1350343241) capitulo/vals-de-prlmavera-20.html http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> vals-de-prlmavera.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('vals de prlmavera 19', 'VALSDEPRlMAVERAOnlineTelenovelaVALSDEPRlMAVERAVerVALSDEPRlMAVERA', 'VALS DE PRlMAVERA Online Telenovela VALS DE PRlMAVERA Ver VALS DE PRlMAVERA', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'A Suh Eun-young (Han Hyo-joo) que vive con su madre soltera en un bello pueblo insular, le piden que cuide de Su-ho, el hijo del amigo de su madre, de su ciudad natal. Su-ho y Eun-young viven juntos y sienten amor fraternal, pero Eun-young, que es de naturaleza enfermiza desde su niñez, llega a un punto crítico de perder su vida si no recibe una operación quirúrgica. Debido a que su familia es extremadamente pobre, son incapaces de pagar los elevados gastos médicos para la hospitalización y el tratamiento quirúrgico y se enfrentan a un callejón sin salida. Afortunadamente, un hombre y su esposa, que desean pagar los gastos médicos de Eun-young, aparecen frente a la familia. Son los padres de Yoon Jae-ha, que hace poco perdieron a su único hijo, internado en el hospital. Ellos proponen pagar los gastos médicos de Eun-young, con la condición de adoptar a Su-ho, quien se parece exactamente a su difunto hijo. Su-ho, que quiere salvar a Eun-young, se marcha a Austria con ellos y Eun-young se recupera totalmente.', 'http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li><li><a href="#tab1_5">Parte 5</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/pS3zECMpGHg&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/3J8Xqk3rxlA&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/U5dN6n-xL6U&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/QTtEr85LM_U&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_5" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/_jcTHqlJBXk&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (2 : 1350343241) capitulo/vals-de-prlmavera-19.html http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> vals-de-prlmavera.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('vals de prlmavera 18', 'VALSDEPRlMAVERAOnlineTelenovelaVALSDEPRlMAVERAVerVALSDEPRlMAVERA', 'VALS DE PRlMAVERA Online Telenovela VALS DE PRlMAVERA Ver VALS DE PRlMAVERA', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'A Suh Eun-young (Han Hyo-joo) que vive con su madre soltera en un bello pueblo insular, le piden que cuide de Su-ho, el hijo del amigo de su madre, de su ciudad natal. Su-ho y Eun-young viven juntos y sienten amor fraternal, pero Eun-young, que es de naturaleza enfermiza desde su niñez, llega a un punto crítico de perder su vida si no recibe una operación quirúrgica. Debido a que su familia es extremadamente pobre, son incapaces de pagar los elevados gastos médicos para la hospitalización y el tratamiento quirúrgico y se enfrentan a un callejón sin salida. Afortunadamente, un hombre y su esposa, que desean pagar los gastos médicos de Eun-young, aparecen frente a la familia. Son los padres de Yoon Jae-ha, que hace poco perdieron a su único hijo, internado en el hospital. Ellos proponen pagar los gastos médicos de Eun-young, con la condición de adoptar a Su-ho, quien se parece exactamente a su difunto hijo. Su-ho, que quiere salvar a Eun-young, se marcha a Austria con ellos y Eun-young se recupera totalmente.', 'http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li><li><a href="#tab1_5">Parte 5</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/x5oDM5BJK3Y&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/XzdwQ_nb-l0&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/lCPfVteZc44&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/KzjdvuFtBy8&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_5" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/CV0lT8oURjU&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (3 : 1350343242) capitulo/vals-de-prlmavera-18.html http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> vals-de-prlmavera.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('vals de prlmavera 17', 'VALSDEPRlMAVERAOnlineTelenovelaVALSDEPRlMAVERAVerVALSDEPRlMAVERA', 'VALS DE PRlMAVERA Online Telenovela VALS DE PRlMAVERA Ver VALS DE PRlMAVERA', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'A Suh Eun-young (Han Hyo-joo) que vive con su madre soltera en un bello pueblo insular, le piden que cuide de Su-ho, el hijo del amigo de su madre, de su ciudad natal. Su-ho y Eun-young viven juntos y sienten amor fraternal, pero Eun-young, que es de naturaleza enfermiza desde su niñez, llega a un punto crítico de perder su vida si no recibe una operación quirúrgica. Debido a que su familia es extremadamente pobre, son incapaces de pagar los elevados gastos médicos para la hospitalización y el tratamiento quirúrgico y se enfrentan a un callejón sin salida. Afortunadamente, un hombre y su esposa, que desean pagar los gastos médicos de Eun-young, aparecen frente a la familia. Son los padres de Yoon Jae-ha, que hace poco perdieron a su único hijo, internado en el hospital. Ellos proponen pagar los gastos médicos de Eun-young, con la condición de adoptar a Su-ho, quien se parece exactamente a su difunto hijo. Su-ho, que quiere salvar a Eun-young, se marcha a Austria con ellos y Eun-young se recupera totalmente.', 'http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li><li><a href="#tab1_5">Parte 5</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/mWPlHH2aPHo&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/Et8URmV-GvA&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/74lW7xrfjX0&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/WLpx_BJR4NQ&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_5" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/OKX6oGk-HbU&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (4 : 1350343242) capitulo/vals-de-prlmavera-17.html http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> vals-de-prlmavera.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('vals de prlmavera 16', 'VALSDEPRlMAVERAOnlineTelenovelaVALSDEPRlMAVERAVerVALSDEPRlMAVERA', 'VALS DE PRlMAVERA Online Telenovela VALS DE PRlMAVERA Ver VALS DE PRlMAVERA', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'A Suh Eun-young (Han Hyo-joo) que vive con su madre soltera en un bello pueblo insular, le piden que cuide de Su-ho, el hijo del amigo de su madre, de su ciudad natal. Su-ho y Eun-young viven juntos y sienten amor fraternal, pero Eun-young, que es de naturaleza enfermiza desde su niñez, llega a un punto crítico de perder su vida si no recibe una operación quirúrgica. Debido a que su familia es extremadamente pobre, son incapaces de pagar los elevados gastos médicos para la hospitalización y el tratamiento quirúrgico y se enfrentan a un callejón sin salida. Afortunadamente, un hombre y su esposa, que desean pagar los gastos médicos de Eun-young, aparecen frente a la familia. Son los padres de Yoon Jae-ha, que hace poco perdieron a su único hijo, internado en el hospital. Ellos proponen pagar los gastos médicos de Eun-young, con la condición de adoptar a Su-ho, quien se parece exactamente a su difunto hijo. Su-ho, que quiere salvar a Eun-young, se marcha a Austria con ellos y Eun-young se recupera totalmente.', 'http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li><li><a href="#tab1_5">Parte 5</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/6cxTdbE7xpg&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/hKibvKGu3LU&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/6mU2SmvzBak&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/9Zm7UlB1vsc&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_5" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/tQTPRbI1kmk&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (5 : 1350343243) capitulo/vals-de-prlmavera-16.html http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> vals-de-prlmavera.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('vals de prlmavera 15', 'VALSDEPRlMAVERAOnlineTelenovelaVALSDEPRlMAVERAVerVALSDEPRlMAVERA', 'VALS DE PRlMAVERA Online Telenovela VALS DE PRlMAVERA Ver VALS DE PRlMAVERA', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'A Suh Eun-young (Han Hyo-joo) que vive con su madre soltera en un bello pueblo insular, le piden que cuide de Su-ho, el hijo del amigo de su madre, de su ciudad natal. Su-ho y Eun-young viven juntos y sienten amor fraternal, pero Eun-young, que es de naturaleza enfermiza desde su niñez, llega a un punto crítico de perder su vida si no recibe una operación quirúrgica. Debido a que su familia es extremadamente pobre, son incapaces de pagar los elevados gastos médicos para la hospitalización y el tratamiento quirúrgico y se enfrentan a un callejón sin salida. Afortunadamente, un hombre y su esposa, que desean pagar los gastos médicos de Eun-young, aparecen frente a la familia. Son los padres de Yoon Jae-ha, que hace poco perdieron a su único hijo, internado en el hospital. Ellos proponen pagar los gastos médicos de Eun-young, con la condición de adoptar a Su-ho, quien se parece exactamente a su difunto hijo. Su-ho, que quiere salvar a Eun-young, se marcha a Austria con ellos y Eun-young se recupera totalmente.', 'http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li><li><a href="#tab1_5">Parte 5</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/hTpFR1mjV3A&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/snzyc3MscIA&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/o_Z0EUh4Oso&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/IpW3voI6McQ&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_5" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/bSP7v0BrkCU&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (6 : 1350343244) capitulo/vals-de-prlmavera-15.html http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> vals-de-prlmavera.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('vals de prlmavera 14', 'VALSDEPRlMAVERAOnlineTelenovelaVALSDEPRlMAVERAVerVALSDEPRlMAVERA', 'VALS DE PRlMAVERA Online Telenovela VALS DE PRlMAVERA Ver VALS DE PRlMAVERA', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'A Suh Eun-young (Han Hyo-joo) que vive con su madre soltera en un bello pueblo insular, le piden que cuide de Su-ho, el hijo del amigo de su madre, de su ciudad natal. Su-ho y Eun-young viven juntos y sienten amor fraternal, pero Eun-young, que es de naturaleza enfermiza desde su niñez, llega a un punto crítico de perder su vida si no recibe una operación quirúrgica. Debido a que su familia es extremadamente pobre, son incapaces de pagar los elevados gastos médicos para la hospitalización y el tratamiento quirúrgico y se enfrentan a un callejón sin salida. Afortunadamente, un hombre y su esposa, que desean pagar los gastos médicos de Eun-young, aparecen frente a la familia. Son los padres de Yoon Jae-ha, que hace poco perdieron a su único hijo, internado en el hospital. Ellos proponen pagar los gastos médicos de Eun-young, con la condición de adoptar a Su-ho, quien se parece exactamente a su difunto hijo. Su-ho, que quiere salvar a Eun-young, se marcha a Austria con ellos y Eun-young se recupera totalmente.', 'http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li><li><a href="#tab1_5">Parte 5</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/CQWDWZoD2bM&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/woaomHUpCuY&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/g1w6tgl_2Yo&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/Mi-j1HthQQk&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_5" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/y9rMN27Lcz0&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (7 : 1350343244) capitulo/vals-de-prlmavera-14.html http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> vals-de-prlmavera.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('vals de prlmavera 13', 'VALSDEPRlMAVERAOnlineTelenovelaVALSDEPRlMAVERAVerVALSDEPRlMAVERA', 'VALS DE PRlMAVERA Online Telenovela VALS DE PRlMAVERA Ver VALS DE PRlMAVERA', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'A Suh Eun-young (Han Hyo-joo) que vive con su madre soltera en un bello pueblo insular, le piden que cuide de Su-ho, el hijo del amigo de su madre, de su ciudad natal. Su-ho y Eun-young viven juntos y sienten amor fraternal, pero Eun-young, que es de naturaleza enfermiza desde su niñez, llega a un punto crítico de perder su vida si no recibe una operación quirúrgica. Debido a que su familia es extremadamente pobre, son incapaces de pagar los elevados gastos médicos para la hospitalización y el tratamiento quirúrgico y se enfrentan a un callejón sin salida. Afortunadamente, un hombre y su esposa, que desean pagar los gastos médicos de Eun-young, aparecen frente a la familia. Son los padres de Yoon Jae-ha, que hace poco perdieron a su único hijo, internado en el hospital. Ellos proponen pagar los gastos médicos de Eun-young, con la condición de adoptar a Su-ho, quien se parece exactamente a su difunto hijo. Su-ho, que quiere salvar a Eun-young, se marcha a Austria con ellos y Eun-young se recupera totalmente.', 'http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li><li><a href="#tab1_5">Parte 5</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/gqhhQ3wB0Wk&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/lBnVWWrCIAw&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/d3Z_o0PZtbk&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/owsh4jf8iiI&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_5" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/fxytzSotZCM&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (8 : 1350343245) capitulo/vals-de-prlmavera-13.html http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> vals-de-prlmavera.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('vals de prlmavera 12', 'VALSDEPRlMAVERAOnlineTelenovelaVALSDEPRlMAVERAVerVALSDEPRlMAVERA', 'VALS DE PRlMAVERA Online Telenovela VALS DE PRlMAVERA Ver VALS DE PRlMAVERA', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'A Suh Eun-young (Han Hyo-joo) que vive con su madre soltera en un bello pueblo insular, le piden que cuide de Su-ho, el hijo del amigo de su madre, de su ciudad natal. Su-ho y Eun-young viven juntos y sienten amor fraternal, pero Eun-young, que es de naturaleza enfermiza desde su niñez, llega a un punto crítico de perder su vida si no recibe una operación quirúrgica. Debido a que su familia es extremadamente pobre, son incapaces de pagar los elevados gastos médicos para la hospitalización y el tratamiento quirúrgico y se enfrentan a un callejón sin salida. Afortunadamente, un hombre y su esposa, que desean pagar los gastos médicos de Eun-young, aparecen frente a la familia. Son los padres de Yoon Jae-ha, que hace poco perdieron a su único hijo, internado en el hospital. Ellos proponen pagar los gastos médicos de Eun-young, con la condición de adoptar a Su-ho, quien se parece exactamente a su difunto hijo. Su-ho, que quiere salvar a Eun-young, se marcha a Austria con ellos y Eun-young se recupera totalmente.', 'http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li><li><a href="#tab1_5">Parte 5</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/7jJXmGW3bwA&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/DZzIoFOFuG8&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/fxW7s5l4eCE&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/FwjdFriBl_g&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_5" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/kKd7pb_Q4QA&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (9 : 1350343247) capitulo/vals-de-prlmavera-12.html http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> vals-de-prlmavera.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('vals de prlmavera 11', 'VALSDEPRlMAVERAOnlineTelenovelaVALSDEPRlMAVERAVerVALSDEPRlMAVERA', 'VALS DE PRlMAVERA Online Telenovela VALS DE PRlMAVERA Ver VALS DE PRlMAVERA', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'A Suh Eun-young (Han Hyo-joo) que vive con su madre soltera en un bello pueblo insular, le piden que cuide de Su-ho, el hijo del amigo de su madre, de su ciudad natal. Su-ho y Eun-young viven juntos y sienten amor fraternal, pero Eun-young, que es de naturaleza enfermiza desde su niñez, llega a un punto crítico de perder su vida si no recibe una operación quirúrgica. Debido a que su familia es extremadamente pobre, son incapaces de pagar los elevados gastos médicos para la hospitalización y el tratamiento quirúrgico y se enfrentan a un callejón sin salida. Afortunadamente, un hombre y su esposa, que desean pagar los gastos médicos de Eun-young, aparecen frente a la familia. Son los padres de Yoon Jae-ha, que hace poco perdieron a su único hijo, internado en el hospital. Ellos proponen pagar los gastos médicos de Eun-young, con la condición de adoptar a Su-ho, quien se parece exactamente a su difunto hijo. Su-ho, que quiere salvar a Eun-young, se marcha a Austria con ellos y Eun-young se recupera totalmente.', 'http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li><li><a href="#tab1_5">Parte 5</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/ShS6UZtjwmY&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/b3BZE9HBzBw&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/DqroZJviyFs&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/0W_Uq9MxoNg&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_5" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/838iuR4_iUA&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (10 : 1350343247) capitulo/vals-de-prlmavera-11.html http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> vals-de-prlmavera.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('vals de prlmavera 10', 'VALSDEPRlMAVERAOnlineTelenovelaVALSDEPRlMAVERAVerVALSDEPRlMAVERA', 'VALS DE PRlMAVERA Online Telenovela VALS DE PRlMAVERA Ver VALS DE PRlMAVERA', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'A Suh Eun-young (Han Hyo-joo) que vive con su madre soltera en un bello pueblo insular, le piden que cuide de Su-ho, el hijo del amigo de su madre, de su ciudad natal. Su-ho y Eun-young viven juntos y sienten amor fraternal, pero Eun-young, que es de naturaleza enfermiza desde su niñez, llega a un punto crítico de perder su vida si no recibe una operación quirúrgica. Debido a que su familia es extremadamente pobre, son incapaces de pagar los elevados gastos médicos para la hospitalización y el tratamiento quirúrgico y se enfrentan a un callejón sin salida. Afortunadamente, un hombre y su esposa, que desean pagar los gastos médicos de Eun-young, aparecen frente a la familia. Son los padres de Yoon Jae-ha, que hace poco perdieron a su único hijo, internado en el hospital. Ellos proponen pagar los gastos médicos de Eun-young, con la condición de adoptar a Su-ho, quien se parece exactamente a su difunto hijo. Su-ho, que quiere salvar a Eun-young, se marcha a Austria con ellos y Eun-young se recupera totalmente.', 'http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li><li><a href="#tab1_5">Parte 5</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/uPBStw3BWvg&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/l03r06q-edE&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/fGXJxuTfDv0&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/eXesysnSCx0&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_5" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/FLhkZSzSgV4&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (11 : 1350343248) capitulo/vals-de-prlmavera-10.html http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> vals-de-prlmavera.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('vals de prlmavera 9', 'VALSDEPRlMAVERAOnlineTelenovelaVALSDEPRlMAVERAVerVALSDEPRlMAVERA', 'VALS DE PRlMAVERA Online Telenovela VALS DE PRlMAVERA Ver VALS DE PRlMAVERA', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'A Suh Eun-young (Han Hyo-joo) que vive con su madre soltera en un bello pueblo insular, le piden que cuide de Su-ho, el hijo del amigo de su madre, de su ciudad natal. Su-ho y Eun-young viven juntos y sienten amor fraternal, pero Eun-young, que es de naturaleza enfermiza desde su niñez, llega a un punto crítico de perder su vida si no recibe una operación quirúrgica. Debido a que su familia es extremadamente pobre, son incapaces de pagar los elevados gastos médicos para la hospitalización y el tratamiento quirúrgico y se enfrentan a un callejón sin salida. Afortunadamente, un hombre y su esposa, que desean pagar los gastos médicos de Eun-young, aparecen frente a la familia. Son los padres de Yoon Jae-ha, que hace poco perdieron a su único hijo, internado en el hospital. Ellos proponen pagar los gastos médicos de Eun-young, con la condición de adoptar a Su-ho, quien se parece exactamente a su difunto hijo. Su-ho, que quiere salvar a Eun-young, se marcha a Austria con ellos y Eun-young se recupera totalmente.', 'http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li><li><a href="#tab1_5">Parte 5</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/Sll5LjcM1tw&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/EyCzfV3B7TY&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/pQqaLf9CniU&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/ALDYxXNiTjQ&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_5" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/Xxc8odafPIk&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (12 : 1350343249) capitulo/vals-de-prlmavera-9.html http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> vals-de-prlmavera.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('vals de prlmavera 8', 'VALSDEPRlMAVERAOnlineTelenovelaVALSDEPRlMAVERAVerVALSDEPRlMAVERA', 'VALS DE PRlMAVERA Online Telenovela VALS DE PRlMAVERA Ver VALS DE PRlMAVERA', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'A Suh Eun-young (Han Hyo-joo) que vive con su madre soltera en un bello pueblo insular, le piden que cuide de Su-ho, el hijo del amigo de su madre, de su ciudad natal. Su-ho y Eun-young viven juntos y sienten amor fraternal, pero Eun-young, que es de naturaleza enfermiza desde su niñez, llega a un punto crítico de perder su vida si no recibe una operación quirúrgica. Debido a que su familia es extremadamente pobre, son incapaces de pagar los elevados gastos médicos para la hospitalización y el tratamiento quirúrgico y se enfrentan a un callejón sin salida. Afortunadamente, un hombre y su esposa, que desean pagar los gastos médicos de Eun-young, aparecen frente a la familia. Son los padres de Yoon Jae-ha, que hace poco perdieron a su único hijo, internado en el hospital. Ellos proponen pagar los gastos médicos de Eun-young, con la condición de adoptar a Su-ho, quien se parece exactamente a su difunto hijo. Su-ho, que quiere salvar a Eun-young, se marcha a Austria con ellos y Eun-young se recupera totalmente.', 'http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li><li><a href="#tab1_5">Parte 5</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/pSwzUI4dIJs&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/Phn22SNm1WM&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/fvhspzFyaiY&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/0oSJ6lHpovA&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_5" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/93m8BcU8XtY&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (13 : 1350343250) capitulo/vals-de-prlmavera-8.html http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> vals-de-prlmavera.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('vals de prlmavera 7', 'VALSDEPRlMAVERAOnlineTelenovelaVALSDEPRlMAVERAVerVALSDEPRlMAVERA', 'VALS DE PRlMAVERA Online Telenovela VALS DE PRlMAVERA Ver VALS DE PRlMAVERA', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'A Suh Eun-young (Han Hyo-joo) que vive con su madre soltera en un bello pueblo insular, le piden que cuide de Su-ho, el hijo del amigo de su madre, de su ciudad natal. Su-ho y Eun-young viven juntos y sienten amor fraternal, pero Eun-young, que es de naturaleza enfermiza desde su niñez, llega a un punto crítico de perder su vida si no recibe una operación quirúrgica. Debido a que su familia es extremadamente pobre, son incapaces de pagar los elevados gastos médicos para la hospitalización y el tratamiento quirúrgico y se enfrentan a un callejón sin salida. Afortunadamente, un hombre y su esposa, que desean pagar los gastos médicos de Eun-young, aparecen frente a la familia. Son los padres de Yoon Jae-ha, que hace poco perdieron a su único hijo, internado en el hospital. Ellos proponen pagar los gastos médicos de Eun-young, con la condición de adoptar a Su-ho, quien se parece exactamente a su difunto hijo. Su-ho, que quiere salvar a Eun-young, se marcha a Austria con ellos y Eun-young se recupera totalmente.', 'http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li><li><a href="#tab1_5">Parte 5</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/fSHvAa7U23Y&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/isZhsrXquJ8&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/8UPpE-k_f2U&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/12LfgH760n4&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_5" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/Xeay1MQSGWI&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (14 : 1350343252) capitulo/vals-de-prlmavera-7.html http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> vals-de-prlmavera.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('vals de prlmavera 6', 'VALSDEPRlMAVERAOnlineTelenovelaVALSDEPRlMAVERAVerVALSDEPRlMAVERA', 'VALS DE PRlMAVERA Online Telenovela VALS DE PRlMAVERA Ver VALS DE PRlMAVERA', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'A Suh Eun-young (Han Hyo-joo) que vive con su madre soltera en un bello pueblo insular, le piden que cuide de Su-ho, el hijo del amigo de su madre, de su ciudad natal. Su-ho y Eun-young viven juntos y sienten amor fraternal, pero Eun-young, que es de naturaleza enfermiza desde su niñez, llega a un punto crítico de perder su vida si no recibe una operación quirúrgica. Debido a que su familia es extremadamente pobre, son incapaces de pagar los elevados gastos médicos para la hospitalización y el tratamiento quirúrgico y se enfrentan a un callejón sin salida. Afortunadamente, un hombre y su esposa, que desean pagar los gastos médicos de Eun-young, aparecen frente a la familia. Son los padres de Yoon Jae-ha, que hace poco perdieron a su único hijo, internado en el hospital. Ellos proponen pagar los gastos médicos de Eun-young, con la condición de adoptar a Su-ho, quien se parece exactamente a su difunto hijo. Su-ho, que quiere salvar a Eun-young, se marcha a Austria con ellos y Eun-young se recupera totalmente.', 'http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li><li><a href="#tab1_5">Parte 5</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/VGWvLeQdhn0&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/ehX8Sv8JDJ0&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/LT4Lrxap8xY&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/D-LTnUNA2vs&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_5" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/m_pWYaqz-OA&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (15 : 1350343254) capitulo/vals-de-prlmavera-6.html http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> vals-de-prlmavera.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('vals de prlmavera 5', 'VALSDEPRlMAVERAOnlineTelenovelaVALSDEPRlMAVERAVerVALSDEPRlMAVERA', 'VALS DE PRlMAVERA Online Telenovela VALS DE PRlMAVERA Ver VALS DE PRlMAVERA', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'A Suh Eun-young (Han Hyo-joo) que vive con su madre soltera en un bello pueblo insular, le piden que cuide de Su-ho, el hijo del amigo de su madre, de su ciudad natal. Su-ho y Eun-young viven juntos y sienten amor fraternal, pero Eun-young, que es de naturaleza enfermiza desde su niñez, llega a un punto crítico de perder su vida si no recibe una operación quirúrgica. Debido a que su familia es extremadamente pobre, son incapaces de pagar los elevados gastos médicos para la hospitalización y el tratamiento quirúrgico y se enfrentan a un callejón sin salida. Afortunadamente, un hombre y su esposa, que desean pagar los gastos médicos de Eun-young, aparecen frente a la familia. Son los padres de Yoon Jae-ha, que hace poco perdieron a su único hijo, internado en el hospital. Ellos proponen pagar los gastos médicos de Eun-young, con la condición de adoptar a Su-ho, quien se parece exactamente a su difunto hijo. Su-ho, que quiere salvar a Eun-young, se marcha a Austria con ellos y Eun-young se recupera totalmente.', 'http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li><li><a href="#tab1_5">Parte 5</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/BEET7rlns9E&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/-c207oryyJw&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/r5YsIW1Az-8&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/6sJmVe9ncmk&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_5" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/afDvVkCMJg4&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (16 : 1350343256) capitulo/vals-de-prlmavera-5.html http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> vals-de-prlmavera.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('vals de prlmavera 4', 'VALSDEPRlMAVERAOnlineTelenovelaVALSDEPRlMAVERAVerVALSDEPRlMAVERA', 'VALS DE PRlMAVERA Online Telenovela VALS DE PRlMAVERA Ver VALS DE PRlMAVERA', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'A Suh Eun-young (Han Hyo-joo) que vive con su madre soltera en un bello pueblo insular, le piden que cuide de Su-ho, el hijo del amigo de su madre, de su ciudad natal. Su-ho y Eun-young viven juntos y sienten amor fraternal, pero Eun-young, que es de naturaleza enfermiza desde su niñez, llega a un punto crítico de perder su vida si no recibe una operación quirúrgica. Debido a que su familia es extremadamente pobre, son incapaces de pagar los elevados gastos médicos para la hospitalización y el tratamiento quirúrgico y se enfrentan a un callejón sin salida. Afortunadamente, un hombre y su esposa, que desean pagar los gastos médicos de Eun-young, aparecen frente a la familia. Son los padres de Yoon Jae-ha, que hace poco perdieron a su único hijo, internado en el hospital. Ellos proponen pagar los gastos médicos de Eun-young, con la condición de adoptar a Su-ho, quien se parece exactamente a su difunto hijo. Su-ho, que quiere salvar a Eun-young, se marcha a Austria con ellos y Eun-young se recupera totalmente.', 'http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li><li><a href="#tab1_5">Parte 5</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/NJBmrEofBHo&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/UYngegLld6g&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/gGF0p4eI7VQ&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/sJl7LGnDVh8&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_5" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/f8rBlOVdQd4&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (17 : 1350343257) capitulo/vals-de-prlmavera-4.html http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> vals-de-prlmavera.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('vals de prlmavera 3', 'VALSDEPRlMAVERAOnlineTelenovelaVALSDEPRlMAVERAVerVALSDEPRlMAVERA', 'VALS DE PRlMAVERA Online Telenovela VALS DE PRlMAVERA Ver VALS DE PRlMAVERA', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'A Suh Eun-young (Han Hyo-joo) que vive con su madre soltera en un bello pueblo insular, le piden que cuide de Su-ho, el hijo del amigo de su madre, de su ciudad natal. Su-ho y Eun-young viven juntos y sienten amor fraternal, pero Eun-young, que es de naturaleza enfermiza desde su niñez, llega a un punto crítico de perder su vida si no recibe una operación quirúrgica. Debido a que su familia es extremadamente pobre, son incapaces de pagar los elevados gastos médicos para la hospitalización y el tratamiento quirúrgico y se enfrentan a un callejón sin salida. Afortunadamente, un hombre y su esposa, que desean pagar los gastos médicos de Eun-young, aparecen frente a la familia. Son los padres de Yoon Jae-ha, que hace poco perdieron a su único hijo, internado en el hospital. Ellos proponen pagar los gastos médicos de Eun-young, con la condición de adoptar a Su-ho, quien se parece exactamente a su difunto hijo. Su-ho, que quiere salvar a Eun-young, se marcha a Austria con ellos y Eun-young se recupera totalmente.', 'http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li><li><a href="#tab1_5">Parte 5</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/CLcheXptRcI&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/Ypl39awJGFs&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/qtWzEseJ9H0&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/5NaQ-_v5wE8&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_5" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/befbkxXqGiw&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (18 : 1350343257) capitulo/vals-de-prlmavera-3.html http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> vals-de-prlmavera.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('vals de prlmavera 2', 'VALSDEPRlMAVERAOnlineTelenovelaVALSDEPRlMAVERAVerVALSDEPRlMAVERA', 'VALS DE PRlMAVERA Online Telenovela VALS DE PRlMAVERA Ver VALS DE PRlMAVERA', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'A Suh Eun-young (Han Hyo-joo) que vive con su madre soltera en un bello pueblo insular, le piden que cuide de Su-ho, el hijo del amigo de su madre, de su ciudad natal. Su-ho y Eun-young viven juntos y sienten amor fraternal, pero Eun-young, que es de naturaleza enfermiza desde su niñez, llega a un punto crítico de perder su vida si no recibe una operación quirúrgica. Debido a que su familia es extremadamente pobre, son incapaces de pagar los elevados gastos médicos para la hospitalización y el tratamiento quirúrgico y se enfrentan a un callejón sin salida. Afortunadamente, un hombre y su esposa, que desean pagar los gastos médicos de Eun-young, aparecen frente a la familia. Son los padres de Yoon Jae-ha, que hace poco perdieron a su único hijo, internado en el hospital. Ellos proponen pagar los gastos médicos de Eun-young, con la condición de adoptar a Su-ho, quien se parece exactamente a su difunto hijo. Su-ho, que quiere salvar a Eun-young, se marcha a Austria con ellos y Eun-young se recupera totalmente.', 'http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li><li><a href="#tab1_5">Parte 5</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/r86fS3A34PQ&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/if-d1amTsqU&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/sXnoRDB01bQ&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/BdRjRSbOKUk&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_5" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/8fN7rReuVPo&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (19 : 1350343258) capitulo/vals-de-prlmavera-2.html http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> vals-de-prlmavera.sql por Alex');


INSERT INTO `peliculas` (`titulo`, `nombre_caratula`, `titulo_original`, `ano`, `genero`, `sinopsis`, `imagen_url`, `frame_src`, `activo`, `reportado_roto`, `fecha_alta`, `fecha_reporte_roto`, `reporte_roto_email`, `reporte_roto_nombre`, `reporte_roto_comentario`, `fecha_ult_visita`, `numero_vistas`, `ult_visita_ip`, `comentarios`) VALUES
('vals de prlmavera 1', 'VALSDEPRlMAVERAOnlineTelenovelaVALSDEPRlMAVERAVerVALSDEPRlMAVERA', 'VALS DE PRlMAVERA Online Telenovela VALS DE PRlMAVERA Ver VALS DE PRlMAVERA', '', 'tv, telenovela, tvnovela, , youtube, vk, dialymotion, video msn', 'A Suh Eun-young (Han Hyo-joo) que vive con su madre soltera en un bello pueblo insular, le piden que cuide de Su-ho, el hijo del amigo de su madre, de su ciudad natal. Su-ho y Eun-young viven juntos y sienten amor fraternal, pero Eun-young, que es de naturaleza enfermiza desde su niñez, llega a un punto crítico de perder su vida si no recibe una operación quirúrgica. Debido a que su familia es extremadamente pobre, son incapaces de pagar los elevados gastos médicos para la hospitalización y el tratamiento quirúrgico y se enfrentan a un callejón sin salida. Afortunadamente, un hombre y su esposa, que desean pagar los gastos médicos de Eun-young, aparecen frente a la familia. Son los padres de Yoon Jae-ha, que hace poco perdieron a su único hijo, internado en el hospital. Ellos proponen pagar los gastos médicos de Eun-young, con la condición de adoptar a Su-ho, quien se parece exactamente a su difunto hijo. Su-ho, que quiere salvar a Eun-young, se marcha a Austria con ellos y Eun-young se recupera totalmente.', 'http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg', '<div class="container">


<ul class="tabs">
<li class="active"><a href="#tab1">Opcion 1</a></li><li><a href="#tab22">Opcion 2</a></li></ul><div class="tab_container">
<div style="display: block;" id="tab1" class="tab_content"><ul class="subtabs"><li><a href="#tab1_1">Parte 1</a></li><li><a href="#tab1_2">Parte 2</a></li><li><a href="#tab1_3">Parte 3</a></li><li><a href="#tab1_4">Parte 4</a></li></ul><div class="subtab_container"><div id="tab1_1" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/lPAVxEVpqvI&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_2" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/Xo40t-CsCkk&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_3" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/WpysIIqDarI&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div><div id="tab1_4" class="subtab_content" style="display: block;"><embed id="youtubePlayer" src="http://www.youtube-nocookie.com/v/t8Z39I9KTZc&hl=en&fs=1&color1=0xfa3bb0&color2=0xfe95ec&showinfo=0&autoplay=0&showsearch=0&rel=0&iv_load_policy=3" type="application/x-shockwave-flash" allowscriptaccess="never" allownetworking="internal" enablejsurl="false" allowfullscreen="true" wmode="transparent" width="680" height="430"></embed></div></div></div><div id="tab22" class="tab_content" style="display: none; "> OPCION NO DISPONIBLE...  </div>




</div>

</div>


<div style="clear:both;"></div></div>', 1, 0, '2012-10-15', '2012-10-15', '', '', '', '2012-10-15', 0, '192.168.1.64', 'progna: ./bajanovela.sh Ver. 0.0.1b (20 : 1350343258) capitulo/vals-de-prlmavera-1.html http://vertelenovelas.net/image_files/vals-de-prlmavera.jpg /home/macuarro/factsys.lo/u3mx.lo/u3mx.com/u3mx-sql >> vals-de-prlmavera.sql por Alex');

